### ISSUE TITLE
Shiny Blender

### ISSUE THREAD

**Issue by ADDD1233** [TangZJ/able-nerf#4]
May I ask how to train the Shiny Blender dataset? I can't find '/data/Shiny Blender/all/transforms_val. json' when running the code

**Comment by TangZJ** [comment]
Hello,

I assume you are referring to the ball scene in the shiny blender dataset. The file ‘transforms_val.json’ can be found from the original ref-nerf dataset folder. 

https://dorverbin.github.io/refnerf/

Hope this helps. 
Cheers

**Comment by ADDD1233** [comment]
> 你好，
> 
> 我假设您指的是 Shiny Blender 数据集中的球场景。文件“transforms_val.json”可以在原始 ref-nerf 数据集文件夹中找到。
> 
> https://dorverbin.github.io/refnerf/
> 
> 希望这能有所帮助。 干杯

Thank you very much for your recovery, but after I downloaded and extracted it from the official website, only the training and testing files were available without verifying the relevant files
![QQ截图20240823123152](https://github.com/user-attachments/assets/f7fb967b-94b7-46e6-91b6-4ef0a0e750df)

**Comment by TangZJ** [comment]
Hello, 

I just recalled that the validation dataset is something that I came up with to check training performance. You can ignore it.

Alternatively, you may select a few images from the test dataset at random to monitor the training progress.

Thanks!

**Comment by ADDD1233** [comment]
> Hello,
> 
> I just recalled that the validation dataset is something that I came up with to check training performance. You can ignore it.
> 
> Alternatively, you may select a few images from the test dataset at random to monitor the training progress.
> 
> Thanks!

Hello!

What could be the possible reason for this situation in shiny blender rendering?

Thank you very much!
![003_rgb](https://github.com/user-attachments/assets/22c03032-69ef-4f20-b711-3fc90d2cb3dd)

**Comment by TangZJ** [comment]
Hi,

The shiny ball dataset background is white unlike the other scenes which
you may verify with.

You have to train on the white background setting.

Thanks!
